# Generated by Django 3.2.3 on 2021-05-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=10),
        ),
    ]
