# Generated by Django 3.2.3 on 2021-05-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('order', '0007_alter_order_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.ManyToManyField(null=True, related_name='_order_order_price_+', to='product.Product'),
        ),
    ]
