# Generated by Django 3.2.3 on 2021-06-10 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_ordercart_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True, verbose_name='purchased datetime')),
                ('shipping_address', models.TextField()),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to='order.ordercart', verbose_name='shopping cart')),
            ],
            options={
                'verbose_name': 'purchase',
                'verbose_name_plural': 'purchases',
                'db_table': 'purchase',
            },
        ),
    ]
