# Generated by Django 3.2.3 on 2021-06-17 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to='order.ordercart'),
        ),
    ]
